---
deployment:
  tasks:
    - export DEPLOYPATH=/home/oa0k98zxdd10/public_html/misterandmisfit.com/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH